brew install git
brew install zsh
brew install mysql
brew install ruby-build
brew install rbenv
brew install elasticsearch
brew install postgres
brew install tmux
brew install yuicompressor
brew install redis
brew install solr
brew install memcached
brew install the_silver_searcher
brew install go
brew install python
brew install fourstore
brew install coreutils
brew install nodejs