brew cask install caskroom/versions/java7
brew cask install firefox
brew cask install google-chrome-beta
brew cask install iterm2-beta
brew cask install sequel-pro
brew cask install textmate
brew cask install skype
brew cask install spotify
brew cask install alfred
brew cask install dropbox
brew cask install vagrant
brew cask install virtualbox
brew cask install sublime-text3
brew cask install virtualbox
brew cask install bartender
brew cask install aerofs
brew cask install mjolnir
brew cask install rubymine
brew cask install steam
brew cask install github
brew cask install intellij-idea-ce
brew cask install vmware-fusion-6
brew cask install stay
brew cask install flash
brew cask install adobe-air
brew cask install font-ubuntu
brew cask install font-ubuntu-mono-powerline
brew cask install brackets
# brew cask install firefox-aurora
# brew cask install dashlane
